spring:
  application:
      name: ecom-application
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#    username: sa
#    password: ''
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomdb
    username: myuser
    password: mypassword
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  info:
    env:
      enabled : true
server:
  shutdown: graceful

info:
  app:
    name: MyNewApp
    description: App built by us
    version: 1.0.0